CREATE TABLE "sample"
(
    "sample_no" VARCHAR(50) not null
    , "sample_no_bkcc" VARCHAR(255) not null
    , "tenant_id" VARCHAR(255) not null
    , "samplename" nvarchar(255)
    , "airbill" VARCHAR2(40)
    , "cancel_code" VARCHAR2(2)
    , "carrier" VARCHAR2(20)
    , "coc_document_seq" NUMBER(12,0)
    , "collect_date" DATE(7)
    , "collect_name" VARCHAR2(50)
    , "collect_phone" VARCHAR2(30)
    , "collect_temp" VARCHAR2(5)
    , "comp_date" date
    , "due_date" DATE(7)
    , "final_result" VARCHAR2(2)
    , "flags" VARCHAR2(30)
    , "folder" VARCHAR2(12)
    , "folder_pos" NUMBER(4,0)
    , "line_item" NUMBER(3,0)
    , "location" VARCHAR2(150)
    , "location_seq" NUMBER(12,0)
    , "manager" VARCHAR2(4)
    , "open_wip_status" VARCHAR2(2)
    , "original_coc" VARCHAR2(20)
    , "original_hsn" NUMBER(12,0)
    , "owner_lab" VARCHAR2(4)
    , "paired_hsn" NUMBER
    , "priority" VARCHAR2(1)
    , "purchase_order" VARCHAR(50)
    , "receive_date" DATE(7) not null
    , "receive_user" VARCHAR2(4)
    , "report_date" DATE(7)
    , "reqnbr" NUMBER(12,0) not null
    , "sample_desc" VARCHAR(max)
    , "sample_type" VARCHAR2(6)
    , "ship_to_seq" NUMBER(12,0)
    , "submitter_seq" NUMBER(12,0)
    , "test_reason" VARCHAR2(2)
    , "turn_code" VARCHAR2(4)
    , "turn_days" NUMBER(3,0)
    , "wip_status" VARCHAR2(2)
    , "last_update" DATE(7)
    , "clientid" VARCHAR2(50)
    , "projectnum" VARCHAR2(255)
    , "site" VARCHAR2(max)
    , "locator" VARCHAR2(20)
    , "qctype" VARCHAR2(10)
    , "collectby" VARCHAR2(20)
    , "receivedate" DATE(7)
    , "collectdate" DATE(7)
    , "tat" NUMBER
    , "duedate" DATE(7)
    , "priorityflag" VARCHAR2(3)
    , "login_seq" NUMBER
    , "prelognum" VARCHAR2(10)
    , "presamplenum" VARCHAR2(20)
    , "expectdate" DATE(7)
    , "orderdate" DATE(7)
    , "recode" nvarchar(50)
    , "logmatrix" nvarchar(50)
    , "clientmatrix" nvarchar(50)
    , "sampleguid" nvarchar(50)
    , "samplealias" nvarchar(255)
    , "sampleregid" nvarchar(255)
    , "isinactive" bit default ((0)) not null
    , "isqcsource" bit default ((0)) not null
    , "istrip" bit default ((0)) not null
    , "numcontainers" int
    , "sampled" datetime
    , "sampledbegin" datetime
    , "timezone" int
    , "ttimezone" nvarchar(100)
    , "minanalyzed" datetime
    , "maxanalyzed" datetime
    , "minrev" datetime
    , "maxrev" datetime
    , "begdepth" real
    , "enddepth" real
    , "depthunits" nvarchar(20)
    , "samplecomments" nvarchar(max)
    , "sampletype" nvarchar(50)
    , "sampledby" nvarchar(50)
    , "samplereceived" datetime
    , "samplereceivedby" nvarchar(50)
    , "samplelogged" datetime
    , "sampleloggedby" nvarchar(50)
    , "latitude" nvarchar(20)
    , "longitude" nvarchar(20)
    , "welldepth" real
    , "casingheight" real
    , "casingdiameter" real
    , "casingtype" nvarchar(25)
    , "elevation" real
    , "gradient" nvarchar(25)
    , "hazinfo" nvarchar(255)
    , "samplememo" nvarchar(max)
    , "sampleinfo1" nvarchar(50)
    , "sampleinfo2" nvarchar(50)
    , "sampleinfo3" nvarchar(50)
    , "sampleinfo4" nvarchar(50)
    , "sampleinfo5" nvarchar(50)
    , "sampleinfo6" nvarchar(50)
    , "sampleinfo7" nvarchar(50)
    , "sampleinfo8" nvarchar(50)
    , "sampleinfo9" nvarchar(50)
    , "sampleinfo10" nvarchar(50)
    , "sampleuserinfo1" nvarchar(50)
    , "sampleuserinfo2" nvarchar(50)
    , "sampleuserinfo3" nvarchar(50)
    , "sampleuserinfo4" nvarchar(50)
    , "sampleuserinfo5" nvarchar(50)
    , "sampleuserinfo6" nvarchar(50)
    , "sampleuserinfo7" nvarchar(50)
    , "sampleuserinfo8" nvarchar(50)
    , "sampleuserinfo9" nvarchar(50)
    , "sampleuserinfo10" nvarchar(50)
    , "fieldph" nvarchar(50)
    , "fieldtemp" nvarchar(50)
    , "fieldflow" nvarchar(50)
    , "fieldcond" nvarchar(50)
    , "fieldrescl" nvarchar(50)
    , "fieldtotcl" nvarchar(50)
    , "fielddo" nvarchar(50)
    , "fieldturb" nvarchar(50)
    , "fielddata1" nvarchar(50)
    , "fielddata2" nvarchar(50)
    , "fielddata3" nvarchar(50)
    , "fielddata4" nvarchar(50)
    , "fielddata5" nvarchar(50)
    , "fielddata6" nvarchar(50)
    , "fielddata7" nvarchar(50)
    , "fielddata8" nvarchar(50)
    , "fielddata9" nvarchar(50)
    , "fielddata10" nvarchar(50)
    , "samplefieldtested" datetime
    , "samplefieldtestedby" nvarchar(50)
    , "legacymatrix" nvarchar(50)
    , "legacysampleid" nvarchar(50)
    , "migrationbatchid" nvarchar(50)
    , "description" VARCHAR2(60)
    , "quotenumref" VARCHAR2(20)
    , "totalprice" NUMBER
    , "lastdate" DATE(7)
    , "lasttool" VARCHAR2(20)
    , "lastuser" VARCHAR2(20)
    , "samp_function" VARCHAR2(1)
    , "designid" VARCHAR2(10)
    , "reportdate" DATE(7)
    , "prelog_exportedon" DATE(7)
    , "original_report_date" DATE(7)
    , "tableid" VARCHAR2(10)
    , "duedate2" DATE(7)
    , "collect_timezone" VARCHAR2(10)
    , "utc_collectdate" DATE(7)
    , "laboratory" nvarchar(255) not null
    , PRIMARY KEY ("sample_no", "sample_no_bkcc", "tenant_id")
);

