--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_test_hroc_n_fb84a2d2
-- Template         :    wsl_sqlserver_proc_dv_perm
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_test_hroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Saturday, July 22, 2023 at 08:26:31
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_test_hroc_n_fb84a2d2].update_s_test_hroc_n_fb84a2d2
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_test_hroc_national]
      ( hk_h_test
      , price
      , surcharge
      , pkey
      , plevel
      , pprodref
      , pmatnumref
      , class
      , cost
      , holddate
      , holddays
      , holdflg
      , duedate
      , duedays
      , location
      , bottles
      , lastdate
      , lasttool
      , lastuser
      , designid
      , comp
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT DISTINCT stage_test_national.hk_h_test AS hk_h_test
           , stage_test_national.price AS price
           , stage_test_national.surcharge AS surcharge
           , stage_test_national.pkey AS pkey
           , stage_test_national.plevel AS plevel
           , stage_test_national.pprodref AS pprodref
           , stage_test_national.pmatnumref AS pmatnumref
           , stage_test_national.class AS class
           , stage_test_national.cost AS cost
           , stage_test_national.holddate AS holddate
           , stage_test_national.holddays AS holddays
           , stage_test_national.holdflg AS holdflg
           , stage_test_national.duedate AS duedate
           , stage_test_national.duedays AS duedays
           , stage_test_national.location AS location
           , stage_test_national.bottles AS bottles
           , stage_test_national.lastdate AS lastdate
           , stage_test_national.lasttool AS lasttool
           , stage_test_national.lastuser AS lastuser
           , stage_test_national.designid AS designid
           , stage_test_national.comp AS comp
           , stage_test_national.dss_change_hash_test_mroc_national AS dss_change_hash
           , stage_test_national.dss_record_source AS dss_record_source
           , stage_test_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_test_national] stage_test_national
    LEFT OUTER JOIN (
            SELECT s_test_hroc_national.hk_h_test
                 , MAX(s_test_hroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_test_hroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_test_hroc_national] s_test_hroc_national
            GROUP BY s_test_hroc_national.hk_h_test
            ) AS current_rows
      ON  stage_test_national.hk_h_test = current_rows.hk_h_test
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_test_hroc_national] s_test_hroc_national
        WHERE  stage_test_national.hk_h_test = s_test_hroc_national.hk_h_test
        AND    stage_test_national.dss_change_hash_test_mroc_national = s_test_hroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_test_hroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_test_hroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_test_hroc_n_fb84a2d2 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

