--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_r_seedpak_aux_20513c28
-- Template         :    wsl_sqlserver_proc_stage
-- Template Version :    8.1.1.0
-- Description      :    Update the EDW 3NF table r_seedpak_auxiliary_lab_lookup
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Wednesday, August 16, 2023 at 11:11:25
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_r_seedpak_aux_20513c28].update_r_seedpak_aux_20513c28
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_merged_count          INTEGER       -- no of records merged
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_update_count          INTEGER       -- no of records updated
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_update_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY


    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 200

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[r_seedpak_auxiliary_lab_lookup]
      ( acctnum
      , tzcode
      , product_prefix
      , date_added
      , last_date
      , last_user
      , last_tool
      , account_prefix
      , dss_record_source
      , dss_load_date
      , dss_create_time
      )
      SELECT  stage_seedpak_auxiliary_lab_lookup.acctnum AS acctnum
           , stage_seedpak_auxiliary_lab_lookup.tzcode AS tzcode
           , stage_seedpak_auxiliary_lab_lookup.product_prefix AS product_prefix
           , stage_seedpak_auxiliary_lab_lookup.date_added AS date_added
           , stage_seedpak_auxiliary_lab_lookup.last_date AS last_date
           , stage_seedpak_auxiliary_lab_lookup.last_user AS last_user
           , stage_seedpak_auxiliary_lab_lookup.last_tool AS last_tool
           , stage_seedpak_auxiliary_lab_lookup.account_prefix AS account_prefix
           , stage_seedpak_auxiliary_lab_lookup.dss_record_source AS dss_record_source
           , stage_seedpak_auxiliary_lab_lookup.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM [TABLEOWNER].[stage_seedpak_auxiliary_lab_lookup] stage_seedpak_auxiliary_lab_lookup
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    SET @p_status = 1
    SET @p_return_msg = 'r_seedpak_auxiliary_lab_lookup updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' records inserted.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_r_seedpak_aux_20513c28 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

