--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_stage_invoice_689811a5
-- Template         :    wsl_sqlserver_proc_dv_stage_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Stage Table table stage_invoice_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Wednesday, March 08, 2023 at 10:44:54
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_stage_invoice_689811a5].update_stage_invoice_689811a5
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[stage_invoice_national]';
    EXEC @v_return_status = sp_executesql @v_sql

    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[stage_invoice_national]
      ( hk_h_invoice
      , invoice_no
      , invoice_no_bkcc
      , tenant_id
      , ponumber
      , invoicedate
      , invoiceref
      , invoicecomm
      , projectnum
      , description
      , status
      , lastdate
      , lasttool
      , lastuser
      , redostatus
      , mas90date
      , original_invoice_date
      , summary_invoice
      , dss_change_hash_invoice_mroc_national
      , dss_record_source
      , dss_load_date
      , dss_create_time)
      SELECT  CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(COALESCE(invoicenum, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_invoice
           , COALESCE(invoicenum, '-1') AS invoice_no
           , 'lims80' AS invoice_no_bkcc
           , 'lims80' AS tenant_id
           , load_invoicedef_national.ponumber AS ponumber
           , load_invoicedef_national.invoicedate AS invoicedate
           , load_invoicedef_national.invoiceref AS invoiceref
           , load_invoicedef_national.invoicecomm AS invoicecomm
           , load_invoicedef_national.projectnum AS projectnum
           , load_invoicedef_national.description AS description
           , load_invoicedef_national.status AS status
           , load_invoicedef_national.lastdate AS lastdate
           , load_invoicedef_national.lasttool AS lasttool
           , load_invoicedef_national.lastuser AS lastuser
           , load_invoicedef_national.redostatus AS redostatus
           , load_invoicedef_national.mas90date AS mas90date
           , load_invoicedef_national.original_invoice_date AS original_invoice_date
           , load_invoicedef_national.summary_invoice AS summary_invoice
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_invoicedef_national.ponumber AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.invoicedate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.invoiceref AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.invoicecomm AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.projectnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.description AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.status AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.lastdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.lasttool AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.lastuser AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.redostatus AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.mas90date AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.original_invoice_date AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_invoicedef_national.summary_invoice AS VARCHAR(MAX)),'null')
               ),2) AS dss_change_hash_invoice_mroc_national
           , load_invoicedef_national.dss_record_source AS dss_record_source
           , load_invoicedef_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM [TABLEOWNER].[load_invoicedef_national] load_invoicedef_national
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 'stage_invoice_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_stage_invoice_689811a5 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
