--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_department__9c6815ed
-- Template         :    wsl_sqlserver_proc_dv_perm
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_department_instrument_run_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, August 15, 2023 at 20:47:14
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_department__9c6815ed].update_s_department__9c6815ed
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_department_instrument_run_mroc_national]
      ( hk_l_department_instrument_run
      , instrument_run_no
      , audit_seq
      , samp_tag
      , login_seq
      , list_joinid
      , snapshot_flag
      , dkey_flag
      , parm_validate_flag
      , dkey_cnt
      , pchain_id
      , calcid
      , process_step
      , process_id
      , nextprocess_id
      , process_status
      , process_message
      , reqavail_flag
      , calcavail_flag
      , approval_status
      , galp_id
      , input_seq
      , inputdate
      , samp_type
      , link_id
      , enterdate
      , prep_date1
      , prep_date2
      , measuredate
      , rptremarks
      , comments
      , lastdate
      , lastuser
      , lasttool
      , analysis_type
      , analysis_count
      , rpt_mdl
      , virtual_set
      , worknum
      , tic
      , run_date
      , run_type
      , analyst
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT DISTINCT stage_department_instrument_run_national.hk_l_department_instrument_run AS hk_l_department_instrument_run
           , stage_department_instrument_run_national.instrument_run_no AS instrument_run_no
           , stage_department_instrument_run_national.audit_seq AS audit_seq
           , stage_department_instrument_run_national.samp_tag AS samp_tag
           , stage_department_instrument_run_national.login_seq AS login_seq
           , stage_department_instrument_run_national.list_joinid AS list_joinid
           , stage_department_instrument_run_national.snapshot_flag AS snapshot_flag
           , stage_department_instrument_run_national.dkey_flag AS dkey_flag
           , stage_department_instrument_run_national.parm_validate_flag AS parm_validate_flag
           , stage_department_instrument_run_national.dkey_cnt AS dkey_cnt
           , stage_department_instrument_run_national.pchain_id AS pchain_id
           , stage_department_instrument_run_national.calcid AS calcid
           , stage_department_instrument_run_national.process_step AS process_step
           , stage_department_instrument_run_national.process_id AS process_id
           , stage_department_instrument_run_national.nextprocess_id AS nextprocess_id
           , stage_department_instrument_run_national.process_status AS process_status
           , stage_department_instrument_run_national.process_message AS process_message
           , stage_department_instrument_run_national.reqavail_flag AS reqavail_flag
           , stage_department_instrument_run_national.calcavail_flag AS calcavail_flag
           , stage_department_instrument_run_national.approval_status AS approval_status
           , stage_department_instrument_run_national.galp_id AS galp_id
           , stage_department_instrument_run_national.input_seq AS input_seq
           , stage_department_instrument_run_national.inputdate AS inputdate
           , stage_department_instrument_run_national.samp_type AS samp_type
           , stage_department_instrument_run_national.link_id AS link_id
           , stage_department_instrument_run_national.enterdate AS enterdate
           , stage_department_instrument_run_national.prep_date1 AS prep_date1
           , stage_department_instrument_run_national.prep_date2 AS prep_date2
           , stage_department_instrument_run_national.measuredate AS measuredate
           , stage_department_instrument_run_national.rptremarks AS rptremarks
           , stage_department_instrument_run_national.comments AS comments
           , stage_department_instrument_run_national.lastdate AS lastdate
           , stage_department_instrument_run_national.lastuser AS lastuser
           , stage_department_instrument_run_national.lasttool AS lasttool
           , stage_department_instrument_run_national.analysis_type AS analysis_type
           , stage_department_instrument_run_national.analysis_count AS analysis_count
           , stage_department_instrument_run_national.rpt_mdl AS rpt_mdl
           , stage_department_instrument_run_national.virtual_set AS virtual_set
           , stage_department_instrument_run_national.worknum AS worknum
           , stage_department_instrument_run_national.tic AS tic
           , stage_department_instrument_run_national.run_date AS run_date
           , stage_department_instrument_run_national.run_type AS run_type
           , stage_department_instrument_run_national.analyst AS analyst
           , stage_department_instrument_run_national.dss_change_hash_department_instrument_run_mroc_national AS dss_change_hash
           , stage_department_instrument_run_national.dss_record_source AS dss_record_source
           , stage_department_instrument_run_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_department_instrument_run_national] stage_department_instrument_run_national
    LEFT OUTER JOIN (
            SELECT s_department_instrument_run_mroc_national.hk_l_department_instrument_run
                 , MAX(s_department_instrument_run_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_department_instrument_run_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_department_instrument_run_mroc_national] s_department_instrument_run_mroc_national
            GROUP BY s_department_instrument_run_mroc_national.hk_l_department_instrument_run
            ) AS current_rows
      ON  stage_department_instrument_run_national.hk_l_department_instrument_run = current_rows.hk_l_department_instrument_run
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_department_instrument_run_mroc_national] s_department_instrument_run_mroc_national
        WHERE  stage_department_instrument_run_national.hk_l_department_instrument_run = s_department_instrument_run_mroc_national.hk_l_department_instrument_run
        AND    stage_department_instrument_run_national.dss_change_hash_department_instrument_run_mroc_national = s_department_instrument_run_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_department_instrument_run_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_department_instrument_run_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_department__9c6815ed FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
