--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_stage_departm_e9ac7679
-- Template         :    wsl_sqlserver_proc_dv_stage_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Stage Table table stage_department_test_schedule_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Thursday, July 13, 2023 at 11:26:32
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_stage_departm_e9ac7679].update_stage_departm_e9ac7679
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[stage_department_test_schedule_national]';
    EXEC @v_return_status = sp_executesql @v_sql

    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[stage_department_test_schedule_national]
      ( hk_l_department_test_schedule
      , hk_h_test
      , hk_h_department
      , test_no
      , test_no_bkcc
      , test_no_tenant_id
      , department_no
      , department_no_bkcc
      , department_no_tenant_id
      , process_status_code
      , process_status_date
      , process_status_batch_no
      , workdate
      , workstatus
      , dprevdeptnum
      , dnextdeptnum
      , lasttool
      , lastuser
      , login_seq
      , priorityflag
      , class
      , dalloc
      , dprice
      , dcost
      , dholddays
      , dholddate
      , dduedays
      , dduedate
      , dss_change_hash_department_test_schedule_hroc_national
      , dss_change_hash_department_test_schedule_lroc_national
      , dss_record_source
      , dss_load_date
      , dss_create_time)
      SELECT  CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(ISNULL(load_orderdetail_national.samplenum,'-1')+'|'+
Coalesce(load_orderdetail_national.prod,'-1')  +

CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_orderdetail_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.deptnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_l_department_test_schedule
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(ISNULL(load_orderdetail_national.samplenum,'-1')+'|'+
Coalesce(load_orderdetail_national.prod,'-1')  +

CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_orderdetail_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_test
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_orderdetail_national.deptnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_department
           , ISNULL(load_orderdetail_national.samplenum,'-1')+'|'+
Coalesce(load_orderdetail_national.prod,'-1')  +

CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS test_no
           , Coalesce(load_orderdetail_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS test_no_bkcc
           , 'lims80' AS test_no_tenant_id
           , load_orderdetail_national.deptnum AS department_no
           , 'lims80' AS department_no_bkcc
           , 'lims80' AS department_no_tenant_id
           , load_orderdetail_national.dstatus AS process_status_code
           , load_orderdetail_national.dstatusdate AS process_status_date
           , load_orderdetail_national.worknum AS process_status_batch_no
           , load_orderdetail_national.workdate AS workdate
           , load_orderdetail_national.workstatus AS workstatus
           , load_orderdetail_national.dprevdeptnum AS dprevdeptnum
           , load_orderdetail_national.dnextdeptnum AS dnextdeptnum
           , load_orderdetail_national.lasttool AS lasttool
           , load_orderdetail_national.lastuser AS lastuser
           , load_orderdetail_national.login_seq AS login_seq
           , load_orderdetail_national.priorityflag AS priorityflag
           , load_orderdetail_national.class AS class
           , load_orderdetail_national.dalloc AS dalloc
           , load_orderdetail_national.dprice AS dprice
           , load_orderdetail_national.dcost AS dcost
           , load_orderdetail_national.dholddays AS dholddays
           , load_orderdetail_national.dholddate AS dholddate
           , load_orderdetail_national.dduedays AS dduedays
           , load_orderdetail_national.dduedate AS dduedate
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_orderdetail_national.dstatus AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dstatusdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.worknum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.workdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.workstatus AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dprevdeptnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dnextdeptnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.lasttool AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.lastuser AS VARCHAR(MAX)),'null')
               ),2) AS dss_change_hash_department_test_schedule_hroc_national
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_orderdetail_national.login_seq AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.priorityflag AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.class AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dalloc AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dprice AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dcost AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dholddays AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dholddate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dduedays AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_orderdetail_national.dduedate AS VARCHAR(MAX)),'null')
               ),2) AS dss_change_hash_department_test_schedule_lroc_national
           , load_ordermast_national.dss_record_source AS dss_record_source
           , load_ordermast_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM [TABLEOWNER].[load_orderdetail_national] load_orderdetail_national
INNER JOIN [TABLEOWNER].[load_ordermast_national] load_ordermast_national
ON load_ordermast_national.samplenum = load_orderdetail_national.samplenum
AND load_ordermast_national.matnum = load_orderdetail_national.matnum
AND load_ordermast_national.prod = load_orderdetail_national.prod
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 'stage_department_test_schedule_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_stage_departm_e9ac7679 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
