--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_stage_analysi_f92491d4
-- Template         :    wsl_sqlserver_proc_dv_stage_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Stage Table table stage_analysis_process_product_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Thursday, August 17, 2023 at 12:19:29
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_stage_analysi_f92491d4].update_stage_analysi_f92491d4
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[stage_analysis_process_product_national]';
    EXEC @v_return_status = sp_executesql @v_sql

    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[stage_analysis_process_product_national]
      ( hk_l_analysis_process_product
      , hk_h_product
      , hk_h_analysis_process
      , analysis_process_code
      , analysis_process_code_bkcc
      , analysis_process_code_tenant_id
      , product_code
      , product_code_bkcc
      , product_code_tenant_id
      , link_id
      , description
      , list_pointer
      , list_func
      , parm_stored
      , pchain_name
      , dss_change_hash_analysis_process_product_mroc_national
      , dss_record_source
      , dss_load_date
      , dss_create_time)
      SELECT  CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(Coalesce(load_prodmast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_prodmast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(ISNULL(listtype, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(ISNULL(listmatclass, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_l_analysis_process_product
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(Coalesce(load_prodmast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_prodmast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_product
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(ISNULL(listtype, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(ISNULL(listmatclass, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_analysis_process
           , ISNULL(listtype, '-1') AS analysis_process_code
           , ISNULL(listmatclass, '-1') AS analysis_process_code_bkcc
           , 'lims80' AS analysis_process_code_tenant_id
           , Coalesce(load_prodmast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS product_code
           , Coalesce(load_prodmast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS product_code_bkcc
           , 'lims80' AS product_code_tenant_id
           , load_listlink_national.link_id AS link_id
           , load_listlink_national.description AS description
           , load_listlink_national.list_pointer AS list_pointer
           , load_listlink_national.list_func AS list_func
           , load_listlink_national.parm_stored AS parm_stored
           , load_listlink_national.pchain_name AS pchain_name
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_listlink_national.link_id AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_listlink_national.description AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_listlink_national.list_pointer AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_listlink_national.list_func AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_listlink_national.parm_stored AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_listlink_national.pchain_name AS VARCHAR(MAX)),'null')
               ),2) AS dss_change_hash_analysis_process_product_mroc_national
           , load_prodmast_national.dss_record_source AS dss_record_source
           , load_prodmast_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM [TABLEOWNER].[load_prodmast_national] load_prodmast_national
INNER JOIN [TABLEOWNER].[load_listlink_national] load_listlink_national
ON load_listlink_national.prod = load_prodmast_national.prod
AND load_listlink_national.matnum = load_prodmast_national.matnum
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 'stage_analysis_process_product_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_stage_analysi_f92491d4 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
