--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_analysis_pr_a7451301
-- Template         :    wsl_sqlserver_proc_dv_perm
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_analysis_process_product_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Thursday, August 17, 2023 at 12:19:31
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_analysis_pr_a7451301].update_s_analysis_pr_a7451301
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_analysis_process_product_mroc_national]
      ( hk_l_analysis_process_product
      , link_id
      , description
      , list_pointer
      , list_func
      , parm_stored
      , pchain_name
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT DISTINCT stage_analysis_process_product_national.hk_l_analysis_process_product AS hk_l_analysis_process_product
           , stage_analysis_process_product_national.link_id AS link_id
           , stage_analysis_process_product_national.description AS description
           , stage_analysis_process_product_national.list_pointer AS list_pointer
           , stage_analysis_process_product_national.list_func AS list_func
           , stage_analysis_process_product_national.parm_stored AS parm_stored
           , stage_analysis_process_product_national.pchain_name AS pchain_name
           , stage_analysis_process_product_national.dss_change_hash_analysis_process_product_mroc_national AS dss_change_hash
           , stage_analysis_process_product_national.dss_record_source AS dss_record_source
           , stage_analysis_process_product_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_analysis_process_product_national] stage_analysis_process_product_national
    LEFT OUTER JOIN (
            SELECT s_analysis_process_product_mroc_national.hk_l_analysis_process_product
                 , MAX(s_analysis_process_product_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_analysis_process_product_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_analysis_process_product_mroc_national] s_analysis_process_product_mroc_national
            GROUP BY s_analysis_process_product_mroc_national.hk_l_analysis_process_product
            ) AS current_rows
      ON  stage_analysis_process_product_national.hk_l_analysis_process_product = current_rows.hk_l_analysis_process_product
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_analysis_process_product_mroc_national] s_analysis_process_product_mroc_national
        WHERE  stage_analysis_process_product_national.hk_l_analysis_process_product = s_analysis_process_product_mroc_national.hk_l_analysis_process_product
        AND    stage_analysis_process_product_national.dss_change_hash_analysis_process_product_mroc_national = s_analysis_process_product_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_analysis_process_product_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_analysis_process_product_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_analysis_pr_a7451301 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
