--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_invoice_mro_11b31c9a
-- Template         :    wsl_sqlserver_proc_dv_perm_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_invoice_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, May 16, 2023 at 13:21:19
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_invoice_mro_11b31c9a].update_s_invoice_mro_11b31c9a
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_invoice_mroc_national]
      ( hk_h_invoice
      , ponumber
      , invoicedate
      , invoiceref
      , invoicecomm
      , projectnum
      , description
      , status
      , lastdate
      , lasttool
      , lastuser
      , redostatus
      , mas90date
      , original_invoice_date
      , summary_invoice
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT --DISTINCT
stage_invoice_national.hk_h_invoice AS hk_h_invoice
           , stage_invoice_national.ponumber AS ponumber
           , stage_invoice_national.invoicedate AS invoicedate
           , stage_invoice_national.invoiceref AS invoiceref
           , stage_invoice_national.invoicecomm AS invoicecomm
           , stage_invoice_national.projectnum AS projectnum
           , stage_invoice_national.description AS description
           , stage_invoice_national.status AS status
           , stage_invoice_national.lastdate AS lastdate
           , stage_invoice_national.lasttool AS lasttool
           , stage_invoice_national.lastuser AS lastuser
           , stage_invoice_national.redostatus AS redostatus
           , stage_invoice_national.mas90date AS mas90date
           , stage_invoice_national.original_invoice_date AS original_invoice_date
           , stage_invoice_national.summary_invoice AS summary_invoice
           , stage_invoice_national.dss_change_hash_invoice_mroc_national AS dss_change_hash
           , stage_invoice_national.dss_record_source AS dss_record_source
           , stage_invoice_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_invoice_national] stage_invoice_national
    LEFT OUTER JOIN (
            SELECT s_invoice_mroc_national.hk_h_invoice
                 , MAX(s_invoice_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_invoice_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_invoice_mroc_national] s_invoice_mroc_national
            GROUP BY s_invoice_mroc_national.hk_h_invoice
            ) AS current_rows
      ON  stage_invoice_national.hk_h_invoice = current_rows.hk_h_invoice
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_invoice_mroc_national] s_invoice_mroc_national
        WHERE  stage_invoice_national.hk_h_invoice = s_invoice_mroc_national.hk_h_invoice
        AND    stage_invoice_national.dss_change_hash_invoice_mroc_national = s_invoice_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_invoice_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_invoice_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_invoice_mro_11b31c9a FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

