--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_customer_mr_ac8cc3a3
-- Template         :    wsl_sqlserver_proc_dv_perm_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_customer_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, May 16, 2023 at 13:21:04
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_customer_mr_ac8cc3a3].update_s_customer_mr_ac8cc3a3
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_customer_mroc_national]
      ( hk_h_customer
      , acctname
      , acctfactor
      , lastdate
      , lasttool
      , lastuser
      , mas90code
      , date_establishd
      , dso
      , customertype
      , creationdate
      , national_acct_flag
      , active
      , sample_state
      , buyer_type
      , market_segment
      , industry_sector
      , pace_excludeinflation
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT --DISTINCT
stage_customer_national.hk_h_customer AS hk_h_customer
           , stage_customer_national.acctname AS acctname
           , stage_customer_national.acctfactor AS acctfactor
           , stage_customer_national.lastdate AS lastdate
           , stage_customer_national.lasttool AS lasttool
           , stage_customer_national.lastuser AS lastuser
           , stage_customer_national.mas90code AS mas90code
           , stage_customer_national.date_establishd AS date_establishd
           , stage_customer_national.dso AS dso
           , stage_customer_national.customertype AS customertype
           , stage_customer_national.creationdate AS creationdate
           , stage_customer_national.national_acct_flag AS national_acct_flag
           , stage_customer_national.active AS active
           , stage_customer_national.sample_state AS sample_state
           , stage_customer_national.buyer_type AS buyer_type
           , stage_customer_national.market_segment AS market_segment
           , stage_customer_national.industry_sector AS industry_sector
           , stage_customer_national.pace_excludeinflation AS pace_excludeinflation
           , stage_customer_national.dss_change_hash_customer_mroc_national AS dss_change_hash
           , stage_customer_national.dss_record_source AS dss_record_source
           , stage_customer_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_customer_national] stage_customer_national
    LEFT OUTER JOIN (
            SELECT s_customer_mroc_national.hk_h_customer
                 , MAX(s_customer_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_customer_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_customer_mroc_national] s_customer_mroc_national
            GROUP BY s_customer_mroc_national.hk_h_customer
            ) AS current_rows
      ON  stage_customer_national.hk_h_customer = current_rows.hk_h_customer
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_customer_mroc_national] s_customer_mroc_national
        WHERE  stage_customer_national.hk_h_customer = s_customer_mroc_national.hk_h_customer
        AND    stage_customer_national.dss_change_hash_customer_mroc_national = s_customer_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_customer_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_customer_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_customer_mr_ac8cc3a3 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

