--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_product_mroc_24d6adc
-- Template         :    wsl_sqlserver_proc_dv_perm_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_product_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, May 16, 2023 at 13:21:23
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_product_mroc_24d6adc].update_s_product_mroc_24d6adc
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_product_mroc_national]
      ( hk_h_product
      , method
      , matrix
      , listtype
      , description
      , class
      , holddays
      , holdflg
      , duedays
      , factorflg
      , containertype
      , bottles
      , lastdate
      , lasttool
      , lastuser
      , costcenter
      , phasecode
      , auto_anrev_flag
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT --DISTINCT
stage_product_national.hk_h_product AS hk_h_product
           , stage_product_national.method AS method
           , stage_product_national.matrix AS matrix
           , stage_product_national.listtype AS listtype
           , stage_product_national.description AS description
           , stage_product_national.class AS class
           , stage_product_national.holddays AS holddays
           , stage_product_national.holdflg AS holdflg
           , stage_product_national.duedays AS duedays
           , stage_product_national.factorflg AS factorflg
           , stage_product_national.containertype AS containertype
           , stage_product_national.bottles AS bottles
           , stage_product_national.lastdate AS lastdate
           , stage_product_national.lasttool AS lasttool
           , stage_product_national.lastuser AS lastuser
           , stage_product_national.costcenter AS costcenter
           , stage_product_national.phasecode AS phasecode
           , stage_product_national.auto_anrev_flag AS auto_anrev_flag
           , stage_product_national.dss_change_hash_product_mroc_national AS dss_change_hash
           , stage_product_national.dss_record_source AS dss_record_source
           , stage_product_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_product_national] stage_product_national
    LEFT OUTER JOIN (
            SELECT s_product_mroc_national.hk_h_product
                 , MAX(s_product_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_product_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_product_mroc_national] s_product_mroc_national
            GROUP BY s_product_mroc_national.hk_h_product
            ) AS current_rows
      ON  stage_product_national.hk_h_product = current_rows.hk_h_product
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_product_mroc_national] s_product_mroc_national
        WHERE  stage_product_national.hk_h_product = s_product_mroc_national.hk_h_product
        AND    stage_product_national.dss_change_hash_product_mroc_national = s_product_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_product_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_product_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_product_mroc_24d6adc FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

