--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_stage_sample__b9547d66
-- Template         :    wsl_sqlserver_proc_dv_stage_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Stage Table table stage_sample_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Wednesday, March 08, 2023 at 10:45:08
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_stage_sample__b9547d66].update_stage_sample__b9547d66
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[stage_sample_national]';
    EXEC @v_return_status = sp_executesql @v_sql

    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[stage_sample_national]
      ( hk_h_sample
      , sample_no
      , sample_no_bkcc
      , tenant_id
      , clientid
      , projectnum
      , site
      , locator
      , qctype
      , collectby
      , receivedate
      , collectdate
      , tat
      , duedate
      , priorityflag
      , login_seq
      , prelognum
      , presamplenum
      , expectdate
      , orderdate
      , samplecomments
      , description
      , quotenumref
      , totalprice
      , lastdate
      , lasttool
      , lastuser
      , samp_function
      , designid
      , reportdate
      , prelog_exportedon
      , original_report_date
      , tableid
      , duedate2
      , collect_timezone
      , utc_collectdate
      , dss_change_hash_sample_mroc_national
      , dss_record_source
      , dss_load_date
      , dss_create_time)
      SELECT  CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_sample_national.samplenum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_sample
           , load_sample_national.samplenum AS sample_no
           , 'lims80' AS sample_no_bkcc
           , 'lims80' AS tenant_id
           , load_sample_national.clientid AS clientid
           , load_sample_national.projectnum AS projectnum
           , load_sample_national.site AS site
           , load_sample_national.locator AS locator
           , load_sample_national.qctype AS qctype
           , load_sample_national.collectby AS collectby
           , load_sample_national.receivedate AS receivedate
           , load_sample_national.collectdate AS collectdate
           , load_sample_national.tat AS tat
           , load_sample_national.duedate AS duedate
           , load_sample_national.priorityflag AS priorityflag
           , load_sample_national.login_seq AS login_seq
           , load_sample_national.prelognum AS prelognum
           , load_sample_national.presamplenum AS presamplenum
           , load_sample_national.expectdate AS expectdate
           , load_sample_national.orderdate AS orderdate
           , load_sample_national.comments AS samplecomments
           , load_sample_national.description AS description
           , load_sample_national.quotenumref AS quotenumref
           , load_sample_national.totalprice AS totalprice
           , load_sample_national.lastdate AS lastdate
           , load_sample_national.lasttool AS lasttool
           , load_sample_national.lastuser AS lastuser
           , load_sample_national.samp_function AS samp_function
           , load_sample_national.designid AS designid
           , load_sample_national.reportdate AS reportdate
           , load_sample_national.prelog_exportedon AS prelog_exportedon
           , load_sample_national.original_report_date AS original_report_date
           , load_sample_national.tableid AS tableid
           , load_sample_national.duedate2 AS duedate2
           , load_sample_national.collect_timezone AS collect_timezone
           , load_sample_national.utc_collectdate AS utc_collectdate
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_sample_national.clientid AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.projectnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.site AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.locator AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.qctype AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.collectby AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.receivedate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.collectdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.tat AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.duedate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.priorityflag AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.login_seq AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.prelognum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.presamplenum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.expectdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.orderdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.comments AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.description AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.quotenumref AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.totalprice AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.lastdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.lasttool AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.lastuser AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.samp_function AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.designid AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.reportdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.prelog_exportedon AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.original_report_date AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.tableid AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.duedate2 AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.collect_timezone AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_sample_national.utc_collectdate AS VARCHAR(MAX)),'null')
               ),2) AS dss_change_hash_sample_mroc_national
           , load_sample_national.dss_record_source AS dss_record_source
           , load_sample_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM [TABLEOWNER].[load_sample_national] load_sample_national
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 'stage_sample_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_stage_sample__b9547d66 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
