--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_sample_mroc__2b5876f
-- Template         :    wsl_sqlserver_proc_dv_perm_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_sample_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, May 16, 2023 at 13:21:34
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_sample_mroc__2b5876f].update_s_sample_mroc__2b5876f
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_sample_mroc_national]
      ( hk_h_sample
      , clientid
      , projectnum
      , site
      , locator
      , qctype
      , collectby
      , receivedate
      , collectdate
      , tat
      , duedate
      , priorityflag
      , login_seq
      , prelognum
      , presamplenum
      , expectdate
      , orderdate
      , samplecomments
      , description
      , quotenumref
      , totalprice
      , lastdate
      , lasttool
      , lastuser
      , samp_function
      , designid
      , reportdate
      , prelog_exportedon
      , original_report_date
      , tableid
      , duedate2
      , collect_timezone
      , utc_collectdate
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT --DISTINCT
stage_sample_national.hk_h_sample AS hk_h_sample
           , stage_sample_national.clientid AS clientid
           , stage_sample_national.projectnum AS projectnum
           , stage_sample_national.site AS site
           , stage_sample_national.locator AS locator
           , stage_sample_national.qctype AS qctype
           , stage_sample_national.collectby AS collectby
           , stage_sample_national.receivedate AS receivedate
           , stage_sample_national.collectdate AS collectdate
           , stage_sample_national.tat AS tat
           , stage_sample_national.duedate AS duedate
           , stage_sample_national.priorityflag AS priorityflag
           , stage_sample_national.login_seq AS login_seq
           , stage_sample_national.prelognum AS prelognum
           , stage_sample_national.presamplenum AS presamplenum
           , stage_sample_national.expectdate AS expectdate
           , stage_sample_national.orderdate AS orderdate
           , stage_sample_national.samplecomments AS samplecomments
           , stage_sample_national.description AS description
           , stage_sample_national.quotenumref AS quotenumref
           , stage_sample_national.totalprice AS totalprice
           , stage_sample_national.lastdate AS lastdate
           , stage_sample_national.lasttool AS lasttool
           , stage_sample_national.lastuser AS lastuser
           , stage_sample_national.samp_function AS samp_function
           , stage_sample_national.designid AS designid
           , stage_sample_national.reportdate AS reportdate
           , stage_sample_national.prelog_exportedon AS prelog_exportedon
           , stage_sample_national.original_report_date AS original_report_date
           , stage_sample_national.tableid AS tableid
           , stage_sample_national.duedate2 AS duedate2
           , stage_sample_national.collect_timezone AS collect_timezone
           , stage_sample_national.utc_collectdate AS utc_collectdate
           , stage_sample_national.dss_change_hash_sample_mroc_national AS dss_change_hash
           , stage_sample_national.dss_record_source AS dss_record_source
           , stage_sample_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_sample_national] stage_sample_national
    LEFT OUTER JOIN (
            SELECT s_sample_mroc_national.hk_h_sample
                 , MAX(s_sample_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_sample_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_sample_mroc_national] s_sample_mroc_national
            GROUP BY s_sample_mroc_national.hk_h_sample
            ) AS current_rows
      ON  stage_sample_national.hk_h_sample = current_rows.hk_h_sample
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_sample_mroc_national] s_sample_mroc_national
        WHERE  stage_sample_national.hk_h_sample = s_sample_mroc_national.hk_h_sample
        AND    stage_sample_national.dss_change_hash_sample_mroc_national = s_sample_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_sample_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_sample_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_sample_mroc__2b5876f FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

