--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_stage_product_3af26223
-- Template         :    wsl_sqlserver_proc_dv_stage_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Stage Table table stage_product_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, August 29, 2023 at 10:32:18
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_stage_product_3af26223].update_stage_product_3af26223
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[stage_product_national]';
    EXEC @v_return_status = sp_executesql @v_sql

    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[stage_product_national]
      ( hk_h_product
      , product_code
      , product_code_bkcc
      , tenant_id
      , method
      , matrix
      , description
      , class
      , holddays
      , holdflg
      , duedays
      , factorflg
      , containertype
      , bottles
      , lastdate
      , lasttool
      , lastuser
      , costcenter
      , phasecode
      , auto_anrev_flag
      , dss_change_hash_product_mroc_national
      , dss_record_source
      , dss_load_date
      , dss_create_time)
      SELECT  CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(Coalesce(load_prodmast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_prodmast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_product
           , Coalesce(load_prodmast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS product_code
           , Coalesce(load_prodmast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS product_code_bkcc
           , 'lims80' AS tenant_id
           , load_prodmast_national.methodref AS method
           , load_prodmast_national.matnum AS matrix
           , load_prodmast_national.description AS description
           , load_prodmast_national.class AS class
           , load_prodmast_national.holddays AS holddays
           , load_prodmast_national.holdflg AS holdflg
           , load_prodmast_national.duedays AS duedays
           , load_prodmast_national.factorflg AS factorflg
           , load_prodmast_national.containertype AS containertype
           , load_prodmast_national.bottles AS bottles
           , load_prodmast_national.lastdate AS lastdate
           , load_prodmast_national.lasttool AS lasttool
           , load_prodmast_national.lastuser AS lastuser
           , load_prodmast_national.costcenter AS costcenter
           , load_prodmast_national.phasecode AS phasecode
           , load_prodmast_national.auto_anrev_flag AS auto_anrev_flag
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(load_prodmast_national.methodref AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.matnum AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.description AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.class AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.holddays AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.holdflg AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.duedays AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.factorflg AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.containertype AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.bottles AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.lastdate AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.lasttool AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.lastuser AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.costcenter AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.phasecode AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(load_prodmast_national.auto_anrev_flag AS VARCHAR(MAX)),'null')
               ),2) AS dss_change_hash_product_mroc_national
           , load_prodmast_national.dss_record_source AS dss_record_source
           , load_prodmast_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM load.[load_prodmast_national] load_prodmast_national
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 'stage_product_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_stage_product_3af26223 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
