--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_stage_workord_48bc529c
-- Template         :    wsl_sqlserver_proc_dv_stage_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Stage Table table stage_workorder_test_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Friday, March 17, 2023 at 13:15:51
-- Author           :
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_stage_workord_48bc529c].update_stage_workord_48bc529c
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================
  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()

  BEGIN TRY

    --=====================================================
    -- Delete existing records
    --=====================================================
    SET @v_step = 200

    SET @v_sql = N'TRUNCATE TABLE [TABLEOWNER].[stage_workorder_test_national]';
    EXEC @v_return_status = sp_executesql @v_sql

    --=====================================================
    -- Insert new records
    --=====================================================
    SET @v_step = 300

    BEGIN TRANSACTION

      INSERT INTO [TABLEOWNER].[stage_workorder_test_national]
      ( hk_l_workorder_test
      , hk_h_test
      , hk_h_work_order
      , work_order_no
      , work_order_no_bkcc
      , work_order_no_tenant_id
      , test_no
      , test_no_bkcc
      , test_no_tenant_id
      , dss_record_source
      , dss_load_date
      , dss_create_time)
      SELECT  CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(ISNULL(load_ordermast_national.samplenum,'-1')+'|'+
Coalesce(load_ordermast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_ordermast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(coalesce(loginnum, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_l_workorder_test
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(ISNULL(load_ordermast_national.samplenum,'-1')+'|'+
Coalesce(load_ordermast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST(Coalesce(load_ordermast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_test
           , CONVERT(NVARCHAR(64),HashBytes('SHA2_256',
               COALESCE(CAST(coalesce(loginnum, '-1') AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null') +'||'+
               COALESCE(CAST('lims80' AS VARCHAR(MAX)),'null')
               ),2) AS hk_h_work_order
           , coalesce(loginnum, '-1') AS work_order_no
           , 'lims80' AS work_order_no_bkcc
           , 'lims80' AS work_order_no_tenant_id
           , ISNULL(load_ordermast_national.samplenum,'-1')+'|'+
Coalesce(load_ordermast_national.prod,'-1') +
CASE WHEN pprodref IS NOT NULL THEN '|'+isnull(pprodref,'-1') ELSE '' END AS test_no
           , Coalesce(load_ordermast_national.matnum,'-1') +
CASE WHEN pmatnumref IS NOT NULL THEN '|'+isnull(pmatnumref,'-1') ELSE '' END AS test_no_bkcc
           , 'lims80' AS test_no_tenant_id
           , load_sample_national.dss_record_source AS dss_record_source
           , load_sample_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_create_time
      FROM [TABLEOWNER].[load_ordermast_national] load_ordermast_national
INNER JOIN [TABLEOWNER].[load_sample_national] load_sample_national
ON load_sample_national.samplenum = load_ordermast_national.samplenum
      ;

      SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 400

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 'stage_workorder_test_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_stage_workord_48bc529c FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0
