--==============================================================================
-- DBMS Name        :    SQL Server
-- Procedure Name   :    update_s_project_mro_931ad786
-- Template         :    wsl_sqlserver_proc_dv_perm_sha256
-- Template Version :    8.5.1.0
-- Description      :    Update the Satellite table s_project_mroc_national
-- Generated by     :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for    :    Pace Analytical Services
-- Generated on     :    Tuesday, May 16, 2023 at 13:21:26
-- Author           :    Paul Cafarella
--==============================================================================
-- Notes / History
--
CREATE PROCEDURE [SCHEMA.update_s_project_mro_931ad786].update_s_project_mro_931ad786
  @p_sequence         INTEGER
, @p_job_name         VARCHAR(256)
, @p_task_name        VARCHAR(256)
, @p_job_id           INTEGER
, @p_task_id          INTEGER
, @p_return_msg       VARCHAR(1024) OUTPUT
, @p_status           INTEGER       OUTPUT

AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages

  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext               VARCHAR(1024) -- Text for audit_trail
  , @v_sql                   NVARCHAR(255) -- Text for SQL statements
  , @v_step                  INTEGER       -- return code
  , @v_insert_count          INTEGER       -- no of records inserted
  , @v_return_status         INTEGER       -- Update result status
  , @v_current_datetime      DATETIME      -- Used for date insert

  --=====================================================
  -- General Variables
  --=====================================================


  --=====================================================
  -- MAIN
  --=====================================================


  SET @v_step = 100

  SET @v_insert_count = 0
  SET @v_current_datetime = GETDATE()


  BEGIN TRY

    --=====================================================
    -- Insert new records
    --=====================================================

    SET @v_step = 200


    BEGIN TRANSACTION


    INSERT INTO [TABLEOWNER].[s_project_mroc_national]
      ( hk_h_project
      , project_name
      , project_desc
      , purchase_order_no
      , site
      , manager
      , sales1code
      , sales1plan
      , sales2code
      , sales2plan
      , termcode
      , lastdate
      , lasttool
      , lastuser
      , permitnum
      , locator
      , comments
      , buyer_type
      , market_segment
      , industry_sector
      , active
      , sample_interval
      , tat
      , tsr
      , basin
      , sample_state
      , client_type
      , acct_alert
      , po_required
      , rpt_quals
      , rpt_mcl
      , ponumber
      , designid
      , source
      , terr
      , county
      , inv_with_rpt
      , webflag
      , rpt_qc
      , webinvflag
      , archive_flag
      , archive_date
      , service
      , rpt_mdl
      , min_invoice_amt
      , report_packet_id
      , historical_data_check
      , rpt_multi_runs
      , container_label_type
      , hdc_level_2
      , uploaded_data_flag
      , certification_program
      , use_repdb_config
      , combine_inv_coc
      , auto_approve_lvl2_report
      , dss_change_hash
      , dss_record_source
      , dss_load_date
      , dss_start_date
      , dss_version
      , dss_create_time)
    SELECT --DISTINCT
stage_project_national.hk_h_project AS hk_h_project
           , stage_project_national.project_name AS project_name
           , stage_project_national.project_desc AS project_desc
           , stage_project_national.purchase_order_no AS purchase_order_no
           , stage_project_national.site AS site
           , stage_project_national.manager AS manager
           , stage_project_national.sales1code AS sales1code
           , stage_project_national.sales1plan AS sales1plan
           , stage_project_national.sales2code AS sales2code
           , stage_project_national.sales2plan AS sales2plan
           , stage_project_national.termcode AS termcode
           , stage_project_national.lastdate AS lastdate
           , stage_project_national.lasttool AS lasttool
           , stage_project_national.lastuser AS lastuser
           , stage_project_national.permitnum AS permitnum
           , stage_project_national.locator AS locator
           , stage_project_national.comments AS comments
           , stage_project_national.buyer_type AS buyer_type
           , stage_project_national.market_segment AS market_segment
           , stage_project_national.industry_sector AS industry_sector
           , stage_project_national.active AS active
           , stage_project_national.sample_interval AS sample_interval
           , stage_project_national.tat AS tat
           , stage_project_national.tsr AS tsr
           , stage_project_national.basin AS basin
           , stage_project_national.sample_state AS sample_state
           , stage_project_national.client_type AS client_type
           , stage_project_national.acct_alert AS acct_alert
           , stage_project_national.po_required AS po_required
           , stage_project_national.rpt_quals AS rpt_quals
           , stage_project_national.rpt_mcl AS rpt_mcl
           , stage_project_national.ponumber AS ponumber
           , stage_project_national.designid AS designid
           , stage_project_national.source AS source
           , stage_project_national.terr AS terr
           , stage_project_national.county AS county
           , stage_project_national.inv_with_rpt AS inv_with_rpt
           , stage_project_national.webflag AS webflag
           , stage_project_national.rpt_qc AS rpt_qc
           , stage_project_national.webinvflag AS webinvflag
           , stage_project_national.archive_flag AS archive_flag
           , stage_project_national.archive_date AS archive_date
           , stage_project_national.service AS service
           , stage_project_national.rpt_mdl AS rpt_mdl
           , stage_project_national.min_invoice_amt AS min_invoice_amt
           , stage_project_national.report_packet_id AS report_packet_id
           , stage_project_national.historical_data_check AS historical_data_check
           , stage_project_national.rpt_multi_runs AS rpt_multi_runs
           , stage_project_national.container_label_type AS container_label_type
           , stage_project_national.hdc_level_2 AS hdc_level_2
           , stage_project_national.uploaded_data_flag AS uploaded_data_flag
           , stage_project_national.certification_program AS certification_program
           , stage_project_national.use_repdb_config AS use_repdb_config
           , stage_project_national.combine_inv_coc AS combine_inv_coc
           , stage_project_national.auto_approve_lvl2_report AS auto_approve_lvl2_report
           , stage_project_national.dss_change_hash_project_mroc_national AS dss_change_hash
           , stage_project_national.dss_record_source AS dss_record_source
           , stage_project_national.dss_load_date AS dss_load_date
           , @v_current_datetime AS dss_start_date
           , ISNULL(current_rows.dss_version,0) + 1 AS dss_version
           , @v_current_datetime AS dss_create_time
    FROM [TABLEOWNER].[stage_project_national] stage_project_national
    LEFT OUTER JOIN (
            SELECT s_project_mroc_national.hk_h_project
                 , MAX(s_project_mroc_national.dss_start_date) AS dss_start_date
                 , MAX(s_project_mroc_national.dss_version) AS dss_version
            FROM   [TABLEOWNER].[s_project_mroc_national] s_project_mroc_national
            GROUP BY s_project_mroc_national.hk_h_project
            ) AS current_rows
      ON  stage_project_national.hk_h_project = current_rows.hk_h_project
    WHERE NOT EXISTS (
        SELECT 1
        FROM   [TABLEOWNER].[s_project_mroc_national] s_project_mroc_national
        WHERE  stage_project_national.hk_h_project = s_project_mroc_national.hk_h_project
        AND    stage_project_national.dss_change_hash_project_mroc_national = s_project_mroc_national.dss_change_hash
        AND    current_rows.dss_start_date = s_project_mroc_national.dss_start_date
        )
    ;


    SELECT @v_insert_count = @@ROWCOUNT

    COMMIT

    --=====================================================
    -- All Done report the results
    --=====================================================
    SET @v_step = 300

    -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
    EXEC [METABASE].WsWrkTask @p_job_id, @p_task_id, @p_sequence,
     @v_insert_count,0,0,0,0,0,0

    SET @p_status = 1
    SET @p_return_msg = 's_project_mroc_national updated. '
      + CONVERT(VARCHAR,@v_insert_count) + ' new records.'

    RETURN 0

  END TRY
  BEGIN CATCH

    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('update_s_project_mro_931ad786 FAILED with error '
      + CONVERT(VARCHAR,ISNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(VARCHAR,ISNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)

  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END

  RETURN 0

