/****** Object:  Table [psa].[load_clients_national]    Script Date: 12/15/2023 2:12:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [psa].[load_clients_national](
	[acctnum] [nvarchar](50) NULL,
	[projectnum] [nvarchar](50) NULL,
	[active] [nvarchar](1) NULL,
	[sample_interval] [decimal](12, 2) NULL,
	[tat] [decimal](12, 2) NULL,
	[tsr] [nvarchar](4) NULL,
	[basin] [tinyint] NULL,
	[sample_state] [nvarchar](2) NULL,
	[client_type] [nvarchar](1) NULL,
	[acct_alert] [nvarchar](1) NULL,
	[po_required] [nvarchar](1) NULL,
	[rpt_quals] [nvarchar](1) NULL,
	[rpt_mcl] [nvarchar](1) NULL,
	[ponumber] [nvarchar](40) NULL,
	[termcode] [nvarchar](10) NULL,
	[designid] [nvarchar](10) NULL,
	[comments] [nvarchar](max) NULL,
	[source] [nvarchar](4) NULL,
	[terr] [nvarchar](2) NULL,
	[county] [nvarchar](50) NULL,
	[inv_with_rpt] [nvarchar](1) NULL,
	[webflag] [nvarchar](1) NULL,
	[rpt_qc] [nvarchar](1) NULL,
	[webinvflag] [nvarchar](1) NULL,
	[archive_flag] [nvarchar](1) NULL,
	[archive_date] [datetime2](7) NULL,
	[service] [nvarchar](4) NULL,
	[rpt_mdl] [nvarchar](1) NULL,
	[min_invoice_amt] [decimal](12, 2) NULL,
	[report_packet_id] [decimal](12, 2) NULL,
	[historical_data_check] [nchar](1) NULL,
	[rpt_multi_runs] [nchar](1) NULL,
	[container_label_type] [nvarchar](20) NULL,
	[hdc_level_2] [nchar](1) NULL,
	[uploaded_data_flag] [nvarchar](20) NULL,
	[lastdate] [datetime2](7) NULL,
	[lastuser] [nvarchar](30) NULL,
	[lasttool] [nvarchar](30) NULL,
	[certification_program] [nvarchar](30) NULL,
	[use_repdb_config] [nvarchar](1) NULL,
	[buyer_type] [nvarchar](20) NULL,
	[market_segment] [nvarchar](20) NULL,
	[industry_sector] [nvarchar](20) NULL,
	[combine_inv_coc] [nvarchar](1) NULL,
	[auto_approve_lvl2_report] [nchar](1) NULL,
	[scinfl_percent] [decimal](12, 2) NULL,
	[dss_record_source] [nvarchar](255) NULL,
	[dss_load_date] [datetime2](7) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
